# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f401f6913496413689eea91c0c55d42f27640122b6abdf99b4a8fdd3581c115414c0c36dee6973ee0e12320de04f6b1c9949111f59b28febbc839388c2fe43f

test:
  secret_key_base: 0c69afc3c4b03d31f0c0d9c87dff0880ce22793cac3015db47f9060e27360723bc8d7a8d70c8c83f07a372d97292b2e2f7efa76e4a34308a2b4ddb7c41d9e859

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
